### ISSUE TITLE
Enviar email para banca

### ISSUE THREAD

**Issue by WaGjUb** [Hedanvisa/ProjetoTCC#10]
Ao clicar no botão de enviar para avaliação implementado na issue "#9 Criar view enviar para avaliação" o link com as fichas o trabalho pdf e os dados do estudante e nome orientador devem ser enviados para o email dos membros da banca.

**Comment by hydrocat** [comment]
Wag, o que são as fichas ??

**Comment by WaGjUb** [comment]
@hydrocat são as fichas que o sistema manda para a banca preencher sobre o aluno
