### ISSUE TITLE
ActionController::UrlGenerationError in SessionsController#create

### ISSUE THREAD

**Issue by hydrocat** [Hedanvisa/ProjetoTCC#11]
No route matches {:action=>"show", :controller=>"trabalhos", :estudante_id=>1, :id=>nil, :notice=>"Bem Vindo"} missing required keys: [:id]
Extracted source (around line #9):

`if usuario && usuario.authenticate(params[:password])
            session[:usuario_id] = usuario.id
            redirect_to estudante_trabalho_path estudante_id: usuario.id, id: usuario.trabalho, notice: "Bem Vindo"
        else
            flash.now.alert = "Senha ou Email inválido"
            render "new"`

**Comment by hensou** [comment]
Já foi fechada? Quando isso acontece?

**Comment by hensou** [comment]
Vou fechar porque não consegui reproduzir o erro, aparentemente já foi concertado em outro commit.
