### ISSUE TITLE
Criar model Parecer

### ISSUE THREAD

**Issue by saviocamacam** [Hedanvisa/ProjetoTCC#28]
Um parecer contem:
- Pagina associada;
- Texto;

Um Parecer pertence a um Trabalho;
Um Trabalho tem muitos Pareceres;
Um Parecer pertence a um Professor;
Um Professor tem muitos Pareceres;

**Comment by hensou** [comment]
Foi fechado em 1e8ac05b811046cf6a904bb0f28ddf98bd81795e
