### ISSUE TITLE
Criar View de submissão de Trabalho

### ISSUE THREAD

**Issue by hydrocat** [Hedanvisa/ProjetoTCC#3]
Criar um template do ruby on rails que contenha campos de entrada do Model de Trabalho para preenchimento do modelo criado de trabalho
Orientador (String) (opcional);
 Banca 1 (String) (opcional);
 Banca 2 (String) (opcional);
Nome do arquivo ;
 Arquivo (file .pdf);
e um botão de submeter.

**Comment by hensou** [comment]
Falta campos para inserção de banca
