### ISSUE TITLE
Criar Model de trabalho

### ISSUE THREAD

**Issue by WaGjUb** [Hedanvisa/ProjetoTCC#4]
O modelo deve conter as seguintes caracteristicas para que possam ser preenchida no formulario da view de trabalho:
- Orientador (String)
- Banca 1 (String)
- Banca 2 (String)
- Titulo do arquivo (String)
- Arquivo (file .pdf)

**Comment by saviocamacam** [comment]
Verificada a ausencia de um atributo "Estado" para certificacao de qual fase o trabalho esta.
