### ISSUE TITLE
Um orientador nao consegue orientar mais do que um trabalho

### ISSUE THREAD

**Issue by hydrocat** [Hedanvisa/ProjetoTCC#40]
A seguinte mensagem procede.
Não foi possível completar o cadastro:
Orientador email já está em uso

**Comment by hydrocat** [comment]
A seguinte mensagem procede.
Não foi possível completar o cadastro:
Orientador email já está em uso

**Comment by hensou** [comment]
Aparentemente esse erro foi corrigido em algum commit anterior, fiz alguns testes junto com @saviocamacam e funcionou normalmente.
