### ISSUE TITLE
Erro ao atualizar arquivo sem declarar bancas

### ISSUE THREAD

**Issue by Monegat** [Hedanvisa/ProjetoTCC#56]
Ao substituir o PDF cadastrado, é permitido enviar arquivo de qualquer formato e gera undefined method `[]' for nil:NilClass para banca;
Em qualquer circunstancia de atualização do trabalho campos para banca 1 e 2 não aparecem para serem atualizados em caso de inexistência.

**Comment by hensou** [comment]
Foi fechado no commit 8d6870a
