### ISSUE TITLE
Implementar o envio automático para o aluno

### ISSUE THREAD

**Issue by WaGjUb** [Hedanvisa/ProjetoTCC#7]
Enviar um email para o aluno contendo: Titulo: "Arquivo (nome do aquivo) submetido" conteúdo: 'NOME DO ALUNO', 'RA' seu trabalho de TCC  "NOME DO TRABALHO" foi submetido na data 'DD/MM/YYYY' para avaliação"

**Comment by hydrocat** [comment]
No meio dos comits, foi perdido o conteudo do email que é enviado para o aluno

**Comment by hydrocat** [comment]
fixed 💯

**Comment by hydrocat** [comment]
reopen porque não comitei as mudanças

**Comment by hydrocat** [comment]
porra, escrevi a mensagem de commit errado, faltou o '#'
